available_entities:
  node: node
  user: user
  block_content: 0
  comment: 0
  contact_message: 0
  file: 0
  profile: 0
  shortcut: 0
  social_auth: 0
  taxonomy_term: 0
  webform_submission: 0
  menu_link_content: 0
  paragraph: 0
_core:
  default_config_hash: w4lg2w4ee2Ig5VjqsctKuiSFEuhYXm2KaAMk6Qg1ZxM
